before_install: git submodule update --init
install: "make test-deps-travis"
script: "make test-main-travis"
notifications:
  email:
    - wakaba.5081@gmail.com
  irc:
    channels:
      - "suika.fam.cx#mechanize"
    use_notice: true
